# Generated by Django 3.0.5 on 2020-04-25 22:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id_materia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=300)),
                ('sigla', models.CharField(max_length=5)),
                ('estudiantes', models.ManyToManyField(related_name='Estudiantes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notas_materias',
            },
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id_nota', models.AutoField(primary_key=True, serialize=False)),
                ('primer_parcial', models.DecimalField(decimal_places=2, max_digits=3)),
                ('segundo_parcial', models.DecimalField(decimal_places=2, max_digits=3)),
                ('examen_final', models.DecimalField(decimal_places=2, max_digits=3)),
                ('controles', models.DecimalField(decimal_places=2, max_digits=3)),
                ('practicos', models.DecimalField(decimal_places=2, max_digits=3)),
                ('fk_alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Alumno', to=settings.AUTH_USER_MODEL)),
                ('fk_materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Materia', to='notas.Materia')),
            ],
            options={
                'db_table': 'notas_notas',
            },
        ),
    ]
