# Generated by Django 3.0.5 on 2020-05-04 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0002_materia_docente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='controles',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='nota',
            name='examen_final',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='nota',
            name='practicos',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='nota',
            name='primer_parcial',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='nota',
            name='segundo_parcial',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
    ]
